<?php


namespace app\member\controller;


use think\Controller;
use think\Session;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->check_Auth();
    }
    public function check_Auth(){
        $isLogin = Session::get("Cipan_Auth");
        if (is_null($isLogin)){
            header('Location: http://127.0.0.6/');
        }
    }
}